version: '3.7'

services:
  tracker_api:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - redis
    networks:
      main_net:
          ipv4_address: 172.28.10.2
  redis:
      image: redis:6.0-alpine
      restart: always
      networks:
        main_net:
          ipv4_address: 172.28.10.5
# networking for the Redis container
networks:
  main_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.10.0/24